//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_apontamento : DbContext
    {
        public db_apontamento()
            : base("name=db_apontamento")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cargo> tb_cargo { get; set; }
        public virtual DbSet<tb_colaborador> tb_colaborador { get; set; }
        public virtual DbSet<tb_escala> tb_escala { get; set; }
        public virtual DbSet<tb_eventos> tb_eventos { get; set; }
        public virtual DbSet<tb_gcm> tb_gcm { get; set; }
        public virtual DbSet<tb_gestor> tb_gestor { get; set; }
        public virtual DbSet<tb_operacao> tb_operacao { get; set; }
        public virtual DbSet<tb_registro_horas> tb_registro_horas { get; set; }
        public virtual DbSet<tb_timesheet> tb_timesheet { get; set; }
    }
}
