//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_colaborador()
        {
            this.tb_timesheet = new HashSet<tb_timesheet>();
        }
    
        public int id_colaborador { get; set; }
        public string nome_colaborador { get; set; }
        public int id_escala { get; set; }
        public decimal valor_hora { get; set; }
        public bool status_colaborador { get; set; }
        public int id_gestor { get; set; }
        public int id_operacao { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public Nullable<int> id_gcm { get; set; }
    
        public virtual tb_cargo tb_cargo { get; set; }
        public virtual tb_escala tb_escala { get; set; }
        public virtual tb_gestor tb_gestor { get; set; }
        public virtual tb_operacao tb_operacao { get; set; }
        public virtual tb_gcm tb_gcm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_timesheet> tb_timesheet { get; set; }
    }
}
