//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_eventos()
        {
            this.tb_registro_horas = new HashSet<tb_registro_horas>();
        }
    
        public int id_evento { get; set; }
        public string codigo_evento { get; set; }
        public string nome_evento { get; set; }
        public string cor_evento { get; set; }
        public string descricao_evento { get; set; }
        public int id_gestor { get; set; }
    
        public virtual tb_gestor tb_gestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_registro_horas> tb_registro_horas { get; set; }
    }
}
