//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_escala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_escala()
        {
            this.tb_colaborador = new HashSet<tb_colaborador>();
        }
    
        public int id_escala { get; set; }
        public string descricao { get; set; }
        public System.TimeSpan hora_entrada { get; set; }
        public System.TimeSpan hora_almoco_inicio { get; set; }
        public System.TimeSpan hora_almoco_fim { get; set; }
        public System.TimeSpan hora_saida { get; set; }
        public string tipo_escala { get; set; }
        public int dayoff_1 { get; set; }
        public int dayoff_2 { get; set; }
        public Nullable<int> domingo_off { get; set; }
        public bool ativo { get; set; }
        public int id_gestor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_colaborador> tb_colaborador { get; set; }
        public virtual tb_gestor tb_gestor { get; set; }
    }
}
