//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_gestor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_gestor()
        {
            this.tb_colaborador = new HashSet<tb_colaborador>();
            this.tb_escala = new HashSet<tb_escala>();
            this.tb_eventos = new HashSet<tb_eventos>();
            this.tb_operacao = new HashSet<tb_operacao>();
        }
    
        public int id_gestor { get; set; }
        public string nome_gestor { get; set; }
        public string email_gestor { get; set; }
        public string senha { get; set; }
        public bool status_gestor { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public int id_cargo { get; set; }
        public int id_gcm { get; set; }
    
        public virtual tb_cargo tb_cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_colaborador> tb_colaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_escala> tb_escala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_eventos> tb_eventos { get; set; }
        public virtual tb_gcm tb_gcm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operacao> tb_operacao { get; set; }
    }
}
