//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_registro_horas
    {
        public int id_registro_horas { get; set; }
        public int id_timesheet { get; set; }
        public System.TimeSpan hora_registro { get; set; }
        public string observacao { get; set; }
        public int id_evento { get; set; }
    
        public virtual tb_eventos tb_eventos { get; set; }
        public virtual tb_timesheet tb_timesheet { get; set; }
    }
}
