//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_timesheet()
        {
            this.tb_registro_horas = new HashSet<tb_registro_horas>();
        }
    
        public int id_timesheet { get; set; }
        public int id_colaborador { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_saida { get; set; }
        public Nullable<System.TimeSpan> hora_almoco_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_almoco_fim { get; set; }
        public string tipo_apontamento { get; set; }
    
        public virtual tb_colaborador tb_colaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_registro_horas> tb_registro_horas { get; set; }
    }
}
